# Generated by Django 3.1.2 on 2020-11-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pescado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, null=True)),
                ('massa', models.CharField(max_length=11, null=True)),
                ('tamanho', models.CharField(max_length=50, null=True)),
                ('imagem', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Pescaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=10)),
                ('hora', models.CharField(max_length=5)),
                ('amigos', models.CharField(max_length=50, null=True)),
                ('localizacao', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=50)),
            ],
        ),
    ]
