# Generated by Django 3.1.2 on 2020-11-01 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pescado_pescaria_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pescado',
            name='quemPescou',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usuario'),
        ),
    ]
