# Generated by Django 3.1.2 on 2020-11-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201101_1205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
