# Generated by Django 3.1.2 on 2020-11-01 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pescado',
            name='data',
        ),
    ]
