# Generated by Django 3.1.2 on 2020-11-02 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_pescado_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pescado',
            name='imagem',
        ),
    ]
