# Generated by Django 3.1.2 on 2020-11-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_pescado_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pescaria',
            old_name='quemPescou',
            new_name='organizador',
        ),
        migrations.AlterField(
            model_name='pescaria',
            name='amigos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pescaria',
            name='hora',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
