# Generated by Django 3.1.2 on 2020-11-03 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
